### ISSUE TITLE
What to do next!!!

### ISSUE THREAD

**Issue by ssyamoako** [vappiah/bacterial-genomics-tutorial#1]
Good day Sir, I have this bacteria ErythromycinA and B  and  it's contigs with about 259 sequences and I have a wild type, and I downloaded a reference Genome. I want to compare these files and find mutations and any similarities in these sequences.. Can I get help. Watching this tutorial I realized that even though you had the contigs you still did assemblying using yml. I got lost. I am new to Bioinformatics . I will be glad if you help me out.
I also watched the BRIG tutorial and wanted to know if I can compare the reference and the sequences.

**Comment by vappiah** [comment]
Hi @ssyamoako 
>  I want to compare these files and find mutations and any similarities in these sequences.

To be able to find mutations , you can use tools like snippy to do that. I am considering doing a video on that soon.
Regions of similarity you can use tools like ClusterO to perform sequence alignment. Then view the alignment results .


>  also watched the BRIG tutorial and wanted to know if I can compare the reference and the sequences.

Yes. BRIG can be used to compare reference genome and other sequences. If you watched the video, you will realize I indicated that one of the sequences was a reference genome.  Also note that BRIG does not work well with a multi-fasta file so each sequence should be in a seperate fasta file.

**Comment by vappiah** [comment]
[https://github.com/tseemann/snippy](url)

**Comment by ssyamoako** [comment]
Thank you very much. I was able to get out the BRIG nicely but i think i can do more. I am really learning a lot thank you.
